# Generated by Django 4.0.4 on 2022-04-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='text',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
